# install libraries
if(!require("shiny")) install.packages("shiny")
if(!require("bslib")) install.packages("bslib")
if(!require("shinythemes")) install.packages("shinythemes")
if(!require("ggplot2")) install.packages("ggplot2")
if(!require("plotly")) install.packages("plotly")
if(!require("readr")) install.packages("readr")
if(!require("rio")) install.packages("rio")
if(!require("tibble")) install.packages("tibble")
if(!require("dplyr")) install.packages("dplyr")
if(!require("tidyr")) install.packages("tidyr")
if(!require("DT")) install.packages("DT")
if(!require("lubridate")) install.packages("lubridate")

# load libraries
library(shiny)
library(bslib)
library(shinythemes)
library(ggplot2)
library(plotly)
library(readr)
library(rio)
library(tibble)
library(dplyr)
library(tidyr)
library(DT)
library(lubridate)